from flask import Flask, redirect

import cx_Oracle
import app.oracleConfig

def init_app():
    app = Flask(__name__, static_folder='../build', static_url_path='/')

    from app.api import bp as api_blueprint
    app.register_blueprint(api_blueprint)

    return app

connection = None
dsn_tns = cx_Oracle.makedsn(oracleConfig.hostname, oracleConfig.port, service_name=oracleConfig.serviceid) 

try:
    connection = cx_Oracle.connect(user=oracleConfig.username, password=oracleConfig.password, dsn=dsn_tns) 
    cursor = connection.cursor()

    cursor.execute("CREATE TABLE people (\
        id NUMBER GENERATED BY DEFAULT AS identity,\
        name VARCHAR2(20)\
        )")

except cx_Oracle.Error as error:
    print(error)
